### ISSUE TITLE
NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider Exception

### ISSUE THREAD

**Issue by simonegiacomelli** [skssfo/http2#1]
Hi, I have an exception running the server task

```
C:\temp\http2-master>gradlew server
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:server
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN$Provider
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:26)
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
        at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:234)
        at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:228)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:402)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:306)
        at sks.samples.http2.netty.util.Util.getSslContext(Util.java:42)
        at sks.samples.http2.netty.server.Server.main(Server.java:29)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN$Provider
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server'.
> Process 'command 'C:\root\JavaApps\jdk1.8.0\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.17 secs
```

**Comment by skssfo** [comment]
Do you have the ALPN library in the jvm boot classpath? You can get the ALPN libs from here - http://mvnrepository.com/artifact/org.mortbay.jetty.alpn/alpn-boot

The version of the ALPN that you need to use depends on the version of JDK. You can find the mapping here - http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions

Modify the build.gradle file to use the correct path to the ALPN lib on your system.

**Comment by simonegiacomelli** [comment]
Hi skssfo, I created a pull request :) hope can help!
